#!/usr/bin/env python3
"""
English Word Adventure
Guess the English word in 5 questions or fewer!
Learn about word origins, parts of speech, and letter patterns.
"""

import random


# --- Word Database ---
# Each word has 13 attributes that players can ask about.
# Attributes:
#   noun              - Is it a noun?
#   verb              - Is it a verb?
#   adjective         - Is it an adjective?
#   one_syllable      - Does it have exactly one syllable?
#   starts_with_vowel - Does it start with a vowel (a, e, i, o, u)?
#   has_double_letters - Contains consecutive repeated letters (ee, ll, ss, ...)?
#   has_silent_letters - Contains a silent letter (k in knight, b in lamb, ...)?
#   latin_or_french_origin - Word originates from Latin or French?
#   related_to_nature - Relates to nature, animals, weather, plants?
#   related_to_emotions - Describes or relates to feelings/emotions?
#   has_prefix        - Has a recognizable prefix (un-, re-, pre-, dis-, ...)?
#   has_suffix        - Has a recognizable suffix (-tion, -ly, -ness, -ment, ...)?
#   common_word       - High-frequency everyday word?

WORDS = [
    # --- Words 1-50 (M1b) ---
    {
        "name": "happy",
        "noun": False, "verb": False, "adjective": True,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": True, "has_silent_letters": False,
        "latin_or_french_origin": False, "related_to_nature": False,
        "related_to_emotions": True, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "feeling or showing pleasure or contentment",
        "example": "She felt happy when she saw her friends.",
        "tip": "'Happy' has double 'p' — many English words double a consonant before adding '-y'.",
    },
    {
        "name": "run",
        "noun": True, "verb": True, "adjective": False,
        "one_syllable": True, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": False, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "to move quickly on foot",
        "example": "I like to run in the park every morning.",
        "tip": "'Run' is both a noun and a verb — 'go for a run' vs 'run fast'.",
    },
    {
        "name": "beautiful",
        "noun": False, "verb": False, "adjective": True,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": True,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": True, "has_prefix": False, "has_suffix": True,
        "common_word": True, "difficulty": "medium",
        "definition": "pleasing the senses or mind aesthetically",
        "example": "The sunset over the ocean was beautiful.",
        "tip": "The 'eau' in 'beautiful' comes from French 'beau' meaning handsome.",
    },
    {
        "name": "knight",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": True, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": True,
        "latin_or_french_origin": False, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "medium",
        "definition": "a medieval warrior who served a lord or king",
        "example": "The knight rode his horse into battle.",
        "tip": "The 'k' in 'knight' is silent — Old English used to pronounce it!",
    },
    {
        "name": "umbrella",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": False, "starts_with_vowel": True,
        "has_double_letters": True, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "medium",
        "definition": "a device used for protection against rain or sun",
        "example": "Don't forget your umbrella — it might rain today.",
        "tip": "'Umbrella' comes from Latin 'umbra' meaning shade or shadow.",
    },
    {
        "name": "tree",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": True, "starts_with_vowel": False,
        "has_double_letters": True, "has_silent_letters": False,
        "latin_or_french_origin": False, "related_to_nature": True,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "a tall plant with a trunk, branches, and leaves",
        "example": "We planted a tree in the backyard.",
        "tip": "'Tree' has the double 'e' pattern — like 'free', 'see', 'bee'.",
    },
    {
        "name": "write",
        "noun": False, "verb": True, "adjective": False,
        "one_syllable": True, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": True,
        "latin_or_french_origin": False, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "to mark letters or words on a surface",
        "example": "Please write your name on the paper.",
        "tip": "The 'w' in 'write' is silent — it's a homophone of 'right'!",
    },
    {
        "name": "adventure",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": False, "starts_with_vowel": True,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": True, "has_prefix": False, "has_suffix": True,
        "common_word": True, "difficulty": "medium",
        "definition": "an unusual and exciting experience or activity",
        "example": "Going camping in the mountains was a great adventure.",
        "tip": "From Latin 'adventura' — the '-ture' suffix turns verbs into nouns.",
    },
    {
        "name": "elephant",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": False, "starts_with_vowel": True,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": True,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "medium",
        "definition": "the largest living land animal with a trunk and tusks",
        "example": "The elephant sprayed water with its trunk.",
        "tip": "'Ph' makes an 'f' sound in English — from Greek 'elephas'.",
    },
    {
        "name": "unhappy",
        "noun": False, "verb": False, "adjective": True,
        "one_syllable": False, "starts_with_vowel": True,
        "has_double_letters": True, "has_silent_letters": False,
        "latin_or_french_origin": False, "related_to_nature": False,
        "related_to_emotions": True, "has_prefix": True, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "not happy; sad or discontented",
        "example": "He was unhappy about the cancelled trip.",
        "tip": "The prefix 'un-' means 'not' — one of the most common English prefixes.",
    },
    {
        "name": "knowledge",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": True,
        "latin_or_french_origin": False, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "hard",
        "definition": "facts, information, and skills acquired through experience or education",
        "example": "Her knowledge of history is impressive.",
        "tip": "The 'k' in 'knowledge' is silent — same pattern as 'know' and 'knee'.",
    },
    {
        "name": "quickly",
        "noun": False, "verb": False, "adjective": False,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": False, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": True,
        "common_word": True, "difficulty": "easy",
        "definition": "at a fast speed; rapidly",
        "example": "She quickly finished her homework.",
        "tip": "The suffix '-ly' turns adjectives into adverbs: quick → quickly.",
    },
    {
        "name": "rain",
        "noun": True, "verb": True, "adjective": False,
        "one_syllable": True, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": False, "related_to_nature": True,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "water that falls from clouds in drops",
        "example": "The rain lasted all afternoon.",
        "tip": "'Rain', 'reign', and 'rein' all sound the same — classic English homophones!",
    },
    {
        "name": "discover",
        "noun": False, "verb": True, "adjective": False,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": True, "has_suffix": False,
        "common_word": True, "difficulty": "medium",
        "definition": "to find something for the first time",
        "example": "Scientists discover new species every year.",
        "tip": "'Dis-' is a Latin prefix meaning 'apart' — discover literally means 'uncover'.",
    },
    {
        "name": "ocean",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": False, "starts_with_vowel": True,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": True,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "a very large expanse of sea",
        "example": "Whales live in the ocean.",
        "tip": "The 'ce' in 'ocean' makes a 'sh' sound — an unusual English spelling pattern.",
    },
    {
        "name": "lamb",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": True, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": True,
        "latin_or_french_origin": False, "related_to_nature": True,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "a young sheep",
        "example": "The lamb followed its mother across the field.",
        "tip": "The 'b' in 'lamb' is silent — same pattern as 'comb', 'thumb', 'climb'.",
    },
    {
        "name": "impossible",
        "noun": False, "verb": False, "adjective": True,
        "one_syllable": False, "starts_with_vowel": True,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": True, "has_suffix": True,
        "common_word": True, "difficulty": "medium",
        "definition": "not able to occur, exist, or be done",
        "example": "Nothing is impossible if you work hard enough.",
        "tip": "The prefix 'im-' is a form of 'in-' (meaning 'not') used before 'b', 'm', 'p'.",
    },
    {
        "name": "flower",
        "noun": True, "verb": True, "adjective": False,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": True,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "the seed-bearing part of a plant, often colorful",
        "example": "She picked a flower from the garden.",
        "tip": "'Flower' and 'flour' are homophones — they used to be the same word!",
    },
    {
        "name": "remember",
        "noun": False, "verb": True, "adjective": False,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": True, "has_prefix": True, "has_suffix": False,
        "common_word": True, "difficulty": "medium",
        "definition": "to have something come into the mind again",
        "example": "Do you remember your first day of school?",
        "tip": "'Re-' means 'again' — to remember is to bring a 'member' (thought) back again.",
    },
    {
        "name": "bright",
        "noun": False, "verb": False, "adjective": True,
        "one_syllable": True, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": True,
        "latin_or_french_origin": False, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "giving out or reflecting a lot of light; shining",
        "example": "The bright sun made everyone squint.",
        "tip": "The 'gh' in 'bright' is silent — same as 'night', 'light', 'right'.",
    },
    {
        "name": "education",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": False, "starts_with_vowel": True,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": True,
        "common_word": True, "difficulty": "medium",
        "definition": "the process of receiving or giving systematic instruction",
        "example": "Education opens doors to new opportunities.",
        "tip": "The suffix '-tion' (pronounced 'shun') is one of the most common noun endings.",
    },
    {
        "name": "cold",
        "noun": True, "verb": False, "adjective": True,
        "one_syllable": True, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": False, "related_to_nature": True,
        "related_to_emotions": True, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "of or at a low temperature",
        "example": "It was so cold that the pond froze over.",
        "tip": "'Cold' is both a noun ('catch a cold') and an adjective ('cold water').",
    },
    {
        "name": "butterfly",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": True, "has_silent_letters": False,
        "latin_or_french_origin": False, "related_to_nature": True,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "medium",
        "definition": "an insect with large colorful wings",
        "example": "A butterfly landed on the flower.",
        "tip": "'Butterfly' is a compound word: 'butter' + 'fly'. Nobody knows why!",
    },
    {
        "name": "accept",
        "noun": False, "verb": True, "adjective": False,
        "one_syllable": False, "starts_with_vowel": True,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "medium",
        "definition": "to agree to receive or take something offered",
        "example": "She decided to accept the job offer.",
        "tip": "Don't confuse 'accept' (verb: to receive) with 'except' (preposition: excluding).",
    },
    {
        "name": "sleep",
        "noun": True, "verb": True, "adjective": False,
        "one_syllable": True, "starts_with_vowel": False,
        "has_double_letters": True, "has_silent_letters": False,
        "latin_or_french_origin": False, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "a natural state of rest for the body and mind",
        "example": "I need eight hours of sleep every night.",
        "tip": "'Sleep' is both a noun and verb — 'a good sleep' vs 'I sleep well'.",
    },
    {
        "name": "mysterious",
        "noun": False, "verb": False, "adjective": True,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": True, "has_prefix": False, "has_suffix": True,
        "common_word": True, "difficulty": "hard",
        "definition": "difficult or impossible to understand, explain, or identify",
        "example": "The old house had a mysterious atmosphere.",
        "tip": "The suffix '-ous' turns nouns into adjectives: mystery → mysterious.",
    },
    {
        "name": "island",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": False, "starts_with_vowel": True,
        "has_double_letters": False, "has_silent_letters": True,
        "latin_or_french_origin": False, "related_to_nature": True,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "medium",
        "definition": "a piece of land surrounded by water",
        "example": "We took a boat to the small island.",
        "tip": "The 's' in 'island' is silent! It was added by mistake — influenced by Latin 'insula'.",
    },
    {
        "name": "return",
        "noun": True, "verb": True, "adjective": False,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": True, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "to come or go back to a place or activity",
        "example": "I will return the book to the library tomorrow.",
        "tip": "'Re-' means 'back' — return literally means 'to turn back'.",
    },
    {
        "name": "gentle",
        "noun": False, "verb": False, "adjective": True,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": True, "has_prefix": False, "has_suffix": True,
        "common_word": True, "difficulty": "easy",
        "definition": "mild in temperament or behavior; kind and tender",
        "example": "Be gentle with the baby kitten.",
        "tip": "From French 'gentil' — the '-le' ending is common in English adjectives.",
    },
    {
        "name": "mountain",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": True,
        "latin_or_french_origin": True, "related_to_nature": True,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "medium",
        "definition": "a large natural elevation of the earth's surface",
        "example": "They climbed the mountain to see the view.",
        "tip": "The 'ai' in 'mountain' makes a short 'i' sound — English spelling is tricky!",
    },
    {
        "name": "disappear",
        "noun": False, "verb": True, "adjective": False,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": True, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": True, "has_suffix": False,
        "common_word": True, "difficulty": "medium",
        "definition": "to cease to be visible; to vanish",
        "example": "The magician made the rabbit disappear.",
        "tip": "'Dis-' means 'not' or 'opposite' — disappear = opposite of appear.",
    },
    {
        "name": "light",
        "noun": True, "verb": True, "adjective": True,
        "one_syllable": True, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": True,
        "latin_or_french_origin": False, "related_to_nature": True,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "the natural agent that makes things visible",
        "example": "The light from the candle filled the room.",
        "tip": "'Light' can be a noun, verb, AND adjective — one of English's most flexible words.",
    },
    {
        "name": "kindness",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": False, "related_to_nature": False,
        "related_to_emotions": True, "has_prefix": False, "has_suffix": True,
        "common_word": True, "difficulty": "easy",
        "definition": "the quality of being friendly, generous, and considerate",
        "example": "Her kindness made everyone feel welcome.",
        "tip": "The suffix '-ness' turns adjectives into nouns: kind → kindness.",
    },
    {
        "name": "whisper",
        "noun": True, "verb": True, "adjective": False,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": False, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "medium",
        "definition": "to speak very softly using one's breath",
        "example": "She had to whisper in the library.",
        "tip": "The 'wh-' in 'whisper' was once pronounced with a puff of air — some dialects still do!",
    },
    {
        "name": "ancient",
        "noun": False, "verb": False, "adjective": True,
        "one_syllable": False, "starts_with_vowel": True,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "medium",
        "definition": "belonging to the very distant past",
        "example": "The ancient ruins were thousands of years old.",
        "tip": "From Latin 'antiquus' via French — the '-ient' ending is a Latin pattern.",
    },
    {
        "name": "storm",
        "noun": True, "verb": True, "adjective": False,
        "one_syllable": True, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": False, "related_to_nature": True,
        "related_to_emotions": True, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "a violent disturbance of the atmosphere with wind and rain",
        "example": "The storm knocked down several trees.",
        "tip": "'Storm' is Germanic — many short, strong English weather words are Germanic.",
    },
    {
        "name": "rebuild",
        "noun": False, "verb": True, "adjective": False,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": False, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": True, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "to build something again after it has been damaged",
        "example": "They had to rebuild the house after the fire.",
        "tip": "'Re-' means 'again' — rebuild, redo, restart all follow this pattern.",
    },
    {
        "name": "tongue",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": True, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": True,
        "latin_or_french_origin": False, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "hard",
        "definition": "the muscular organ in the mouth used for tasting and speaking",
        "example": "The doctor asked me to stick out my tongue.",
        "tip": "The 'ue' at the end of 'tongue' is silent — one of English's trickiest spellings.",
    },
    {
        "name": "joyful",
        "noun": False, "verb": False, "adjective": True,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": True, "has_prefix": False, "has_suffix": True,
        "common_word": True, "difficulty": "easy",
        "definition": "feeling, expressing, or causing great pleasure and happiness",
        "example": "It was a joyful celebration for the whole family.",
        "tip": "The suffix '-ful' means 'full of' — joyful = full of joy.",
    },
    {
        "name": "wolf",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": True, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": False, "related_to_nature": True,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "a wild carnivorous mammal related to the dog",
        "example": "The wolf howled at the moon.",
        "tip": "Plural is 'wolves' — English changes 'f' to 'v' before adding '-es' (wife/wives, leaf/leaves).",
    },
    {
        "name": "precious",
        "noun": False, "verb": False, "adjective": True,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": True, "has_prefix": False, "has_suffix": True,
        "common_word": True, "difficulty": "medium",
        "definition": "of great value; not to be wasted or treated carelessly",
        "example": "Time is precious — use it wisely.",
        "tip": "The '-ious' suffix (from Latin) is common in adjectives: precious, curious, serious.",
    },
    {
        "name": "eagle",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": False, "starts_with_vowel": True,
        "has_double_letters": False, "has_silent_letters": True,
        "latin_or_french_origin": True, "related_to_nature": True,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": True,
        "common_word": True, "difficulty": "easy",
        "definition": "a large bird of prey with keen eyesight",
        "example": "The eagle soared high above the valley.",
        "tip": "The 'le' at the end is a common English pattern — eagle, table, little, apple.",
    },
    {
        "name": "predict",
        "noun": False, "verb": True, "adjective": False,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": True, "has_suffix": False,
        "common_word": True, "difficulty": "medium",
        "definition": "to say what will happen in the future",
        "example": "Can you predict who will win the game?",
        "tip": "'Pre-' means 'before' and 'dict' means 'say' — predict = say beforehand.",
    },
    {
        "name": "angry",
        "noun": False, "verb": False, "adjective": True,
        "one_syllable": False, "starts_with_vowel": True,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": False, "related_to_nature": False,
        "related_to_emotions": True, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "feeling or showing strong annoyance or hostility",
        "example": "He was angry because someone broke his toy.",
        "tip": "'Angry' comes from Old Norse 'angr' meaning grief — Vikings influenced English!",
    },
    {
        "name": "scissors",
        "noun": True, "verb": False, "adjective": False,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": True, "has_silent_letters": True,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "hard",
        "definition": "a cutting instrument with two blades",
        "example": "Use scissors to cut along the dotted line.",
        "tip": "The 'sc' makes an 's' sound (the 'c' is silent) — 'scissors' is always plural!",
    },
    {
        "name": "freeze",
        "noun": True, "verb": True, "adjective": False,
        "one_syllable": True, "starts_with_vowel": False,
        "has_double_letters": True, "has_silent_letters": False,
        "latin_or_french_origin": False, "related_to_nature": True,
        "related_to_emotions": False, "has_prefix": False, "has_suffix": False,
        "common_word": True, "difficulty": "easy",
        "definition": "to turn from liquid to solid by cold temperature",
        "example": "Water will freeze at zero degrees Celsius.",
        "tip": "Irregular past tense: freeze → froze → frozen. Many old Germanic verbs are irregular.",
    },
    {
        "name": "comfortable",
        "noun": False, "verb": False, "adjective": True,
        "one_syllable": False, "starts_with_vowel": False,
        "has_double_letters": False, "has_silent_letters": True,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": True, "has_prefix": False, "has_suffix": True,
        "common_word": True, "difficulty": "medium",
        "definition": "providing physical ease and relaxation",
        "example": "This chair is very comfortable.",
        "tip": "Most people say 'COMF-ter-ble' (3 syllables) — the 'or' is often silent in speech.",
    },
    {
        "name": "explore",
        "noun": False, "verb": True, "adjective": False,
        "one_syllable": False, "starts_with_vowel": True,
        "has_double_letters": False, "has_silent_letters": False,
        "latin_or_french_origin": True, "related_to_nature": False,
        "related_to_emotions": False, "has_prefix": True, "has_suffix": False,
        "common_word": True, "difficulty": "medium",
        "definition": "to travel through an unfamiliar area to learn about it",
        "example": "We love to explore new places on vacation.",
        "tip": "'Ex-' means 'out' — explore originally meant 'to search out'.",
    },
    # --- Words 51-100 will be added in M1c ---
]

QUESTIONS = [
    ("Is it a noun?", "noun"),
    ("Is it a verb?", "verb"),
    ("Is it an adjective?", "adjective"),
    ("Does it have exactly one syllable?", "one_syllable"),
    ("Does it start with a vowel?", "starts_with_vowel"),
    ("Does it have double letters (like 'ee' or 'll')?", "has_double_letters"),
    ("Does it have any silent letters?", "has_silent_letters"),
    ("Does it come from Latin or French?", "latin_or_french_origin"),
    ("Is it related to nature?", "related_to_nature"),
    ("Is it related to emotions or feelings?", "related_to_emotions"),
    ("Does it have a prefix (like 'un-' or 're-')?", "has_prefix"),
    ("Does it have a suffix (like '-tion' or '-ly')?", "has_suffix"),
    ("Is it a common everyday word?", "common_word"),
]

MAX_QUESTIONS = 5


# --- Game Functions (to be implemented in M1c / M2 / M3) ---


if __name__ == "__main__":
    pass
