const Data = {
  W: 1280,
  H: 800,
  STARTING_CASH: 100000,
  TICK_MS: 2500,

  NEIGHBORHOODS: [
    {
      id: 'downtown', name: 'Downtown', x: 420, y: 90, w: 210, h: 145,
      type: 'business', volume: 'high', cost: 50000, color: 0x2980b9,
      rent: 2500, demographics: 'Busy professionals. Prefer thin crust, quick service.',
      prefs: { thin: 0.6, thick: 0.2, stuffed: 0.1, wholegrain: 0.1 },
      toppingPrefs: ['anchovies', 'truffle', 'shrimp', 'gorgonzola'],
    },
    {
      id: 'university', name: 'University', x: 660, y: 70, w: 185, h: 155,
      type: 'student', volume: 'high', cost: 28000, color: 0x27ae60,
      rent: 1400, demographics: 'Students. Value deals, stuffed crust, late hours.',
      prefs: { thin: 0.2, thick: 0.3, stuffed: 0.4, wholegrain: 0.1 },
      toppingPrefs: ['pepperoni', 'mozzarella', 'sausage', 'ham'],
    },
    {
      id: 'suburbs', name: 'Suburbs', x: 130, y: 280, w: 230, h: 175,
      type: 'family', volume: 'medium', cost: 22000, color: 0xf39c12,
      rent: 1100, demographics: 'Families. Large portions, kid-friendly, value for money.',
      prefs: { thin: 0.2, thick: 0.5, stuffed: 0.2, wholegrain: 0.1 },
      toppingPrefs: ['ham', 'mozzarella', 'pepper', 'mushroom'],
    },
    {
      id: 'uptown', name: 'Uptown', x: 880, y: 130, w: 200, h: 165,
      type: 'upscale', volume: 'medium', cost: 75000, color: 0x8e44ad,
      rent: 3750, demographics: 'Wealthy residents. Premium only. Ambiance matters.',
      prefs: { thin: 0.7, thick: 0.2, stuffed: 0.05, wholegrain: 0.05 },
      toppingPrefs: ['truffle', 'lobster', 'gorgonzola', 'shrimp'],
    },
    {
      id: 'industrial', name: 'Industrial', x: 280, y: 490, w: 255, h: 155,
      type: 'worker', volume: 'high', cost: 18000, color: 0x7f8c8d,
      rent: 900, demographics: 'Blue-collar workers. Big, cheap, filling. No frills.',
      prefs: { thin: 0.1, thick: 0.5, stuffed: 0.3, wholegrain: 0.1 },
      toppingPrefs: ['sausage', 'pepperoni', 'ham', 'mozzarella'],
    },
    {
      id: 'harbor', name: 'Harbor District', x: 680, y: 430, w: 225, h: 175,
      type: 'tourist', volume: 'medium', cost: 38000, color: 0x16a085,
      rent: 1900, demographics: 'Tourists and fishermen. Seafood toppings, adventurous.',
      prefs: { thin: 0.35, thick: 0.3, stuffed: 0.25, wholegrain: 0.1 },
      toppingPrefs: ['anchovies', 'shrimp', 'lobster', 'olive'],
    },
    {
      id: 'old_quarter', name: 'Old Quarter', x: 940, y: 380, w: 185, h: 155,
      type: 'mixed', volume: 'medium', cost: 33000, color: 0xc0392b,
      rent: 1650, demographics: 'Diverse community. Appreciate exotic, spicy combinations.',
      prefs: { thin: 0.3, thick: 0.3, stuffed: 0.25, wholegrain: 0.15 },
      toppingPrefs: ['spicy', 'onion', 'pepper', 'chicken'],
    },
  ],

  INGREDIENTS: {
    dough: [
      { id: 'thin',      name: 'Thin Crust',    cost: 1.5, color: 0xf5cba7 },
      { id: 'thick',     name: 'Thick Crust',   cost: 2.2, color: 0xe59866 },
      { id: 'stuffed',   name: 'Stuffed Crust', cost: 3.2, color: 0xd4ac0d },
      { id: 'wholegrain',name: 'Whole Grain',   cost: 2.8, color: 0xa9795d },
    ],
    sauce: [
      { id: 'tomato', name: 'Classic Tomato',    cost: 0.8,  color: 0xe74c3c },
      { id: 'bbq',    name: 'BBQ',               cost: 1.3,  color: 0x935116 },
      { id: 'white',  name: 'White Garlic',      cost: 1.6,  color: 0xfdfefe },
      { id: 'spicy',  name: 'Spicy Arrabbiata',  cost: 1.1,  color: 0xcb4335 },
      { id: 'pesto',  name: 'Pesto',             cost: 2.1,  color: 0x1e8449 },
    ],
    toppings: [
      { id: 'mozzarella', name: 'Mozzarella',      cost: 1.5, category: 'cheese',  color: 0xfdfefe },
      { id: 'cheddar',    name: 'Cheddar',         cost: 1.2, category: 'cheese',  color: 0xf39c12 },
      { id: 'gorgonzola', name: 'Gorgonzola',      cost: 2.6, category: 'cheese',  color: 0x7d6608 },
      { id: 'pepperoni',  name: 'Pepperoni',       cost: 2.0, category: 'meat',    color: 0xa93226 },
      { id: 'sausage',    name: 'Italian Sausage', cost: 2.3, category: 'meat',    color: 0x784212 },
      { id: 'ham',        name: 'Ham',             cost: 1.8, category: 'meat',    color: 0xe8a0bf },
      { id: 'chicken',    name: 'Grilled Chicken', cost: 2.5, category: 'meat',    color: 0xf5cba7 },
      { id: 'anchovies',  name: 'Anchovies',       cost: 1.6, category: 'seafood', color: 0x1a5276 },
      { id: 'shrimp',     name: 'Shrimp',          cost: 3.6, category: 'seafood', color: 0xf1948a },
      { id: 'lobster',    name: 'Lobster',         cost: 8.5, category: 'premium', color: 0xe74c3c },
      { id: 'mushroom',   name: 'Mushrooms',       cost: 0.9, category: 'veggie',  color: 0x935116 },
      { id: 'pepper',     name: 'Bell Peppers',    cost: 0.7, category: 'veggie',  color: 0x1e8449 },
      { id: 'olive',      name: 'Black Olives',    cost: 0.9, category: 'veggie',  color: 0x17202a },
      { id: 'onion',      name: 'Red Onion',       cost: 0.5, category: 'veggie',  color: 0x8e44ad },
      { id: 'truffle',    name: 'Truffle Oil',     cost: 5.2, category: 'premium', color: 0x4a235a },
    ],
  },

  STAFF_TYPES: [
    { id: 'cook',    name: 'Cook',    wage: 900,  effect: 'quality',    desc: '+quality, more recipes' },
    { id: 'waiter',  name: 'Waiter',  wage: 650,  effect: 'speed',      desc: '+customers served/day' },
    { id: 'manager', name: 'Manager', wage: 1600, effect: 'efficiency', desc: '+20% overall revenue' },
    { id: 'cleaner', name: 'Cleaner', wage: 520,  effect: 'hygiene',    desc: 'reduces inspection risk' },
  ],

  FURNITURE: [
    { id: 'table_basic', name: 'Basic Table',   cost: 500,   seats: 4,  quality: 1, type: 'seating' },
    { id: 'table_nice',  name: 'Nice Table',    cost: 1300,  seats: 4,  quality: 2, type: 'seating' },
    { id: 'booth',       name: 'Booth',         cost: 2200,  seats: 6,  quality: 2, type: 'seating' },
    { id: 'vip_table',   name: 'VIP Table',     cost: 5500,  seats: 4,  quality: 3, type: 'seating' },
    { id: 'counter',     name: 'Counter Seat',  cost: 350,   seats: 2,  quality: 1, type: 'seating' },
    { id: 'oven_basic',  name: 'Basic Oven',    cost: 3200,  cap: 2,               type: 'kitchen' },
    { id: 'oven_pro',    name: 'Pro Oven',      cost: 8500,  cap: 5,               type: 'kitchen' },
    { id: 'fridge',      name: 'Walk-in Fridge',cost: 4000,  freshness: 2,         type: 'kitchen' },
    { id: 'decor_plant', name: 'Plants',        cost: 220,   ambiance: 1,          type: 'decor'   },
    { id: 'decor_art',   name: 'Wall Art',      cost: 900,   ambiance: 2,          type: 'decor'   },
    { id: 'decor_neon',  name: 'Neon Sign',     cost: 1500,  ambiance: 2,          type: 'decor'   },
    { id: 'decor_fountain', name: 'Fountain',   cost: 3500,  ambiance: 3,          type: 'decor'   },
  ],

  RIVALS: [
    {
      id: 'mafia_mike', name: "Mafia Mike's Pies", shortName: "Mike's",
      color: 0xff4444, personality: 'aggressive', aggression: 0.8,
      startNeighborhood: 'industrial',
      description: "Connected to the Falcone family. Uses 'persuasive' business tactics.",
      taunt: "Nice restaurant. Be a shame if somethin' happened to it.",
    },
    {
      id: 'bella_roma', name: 'Bella Roma', shortName: 'Bella Roma',
      color: 0x44cc44, personality: 'quality', aggression: 0.3,
      startNeighborhood: 'uptown',
      description: 'Established family business. Premium ingredients, 30-year reputation.',
      taunt: "Your pizza couldn't fool a tourist.",
    },
    {
      id: 'pizza_king', name: 'Pizza King Corp.', shortName: 'Pizza King',
      color: 0xffaa00, personality: 'volume', aggression: 0.65,
      startNeighborhood: 'suburbs',
      description: 'Soulless corporate chain. Cheap prices, relentless expansion.',
      taunt: 'Our lawyers look forward to hearing from you.',
    },
  ],

  CRIME_CONTACTS: [
    {
      id: 'inspector_joe', name: 'Inspector Joe', icon: '🧑‍💼',
      type: 'bribe', recurring: true,
      cost: 600, monthlyCost: 600,
      description: 'City health inspector. $600/month keeps your kitchens "pristine."',
      effect: 'no_inspections',
      heatGain: 8,
      unlock: 0,
    },
    {
      id: 'tommy', name: 'Tommy Two-Fingers', icon: '🔨',
      type: 'sabotage', recurring: false,
      cost: 2500, monthlyCost: 0,
      description: 'Professional problem-solver. Rivals suffer mysterious "accidents."',
      effect: 'sabotage_rival',
      heatGain: 25,
      unlock: 0,
    },
    {
      id: 'councilman_reed', name: 'Councilman Reed', icon: '🏛️',
      type: 'permit', recurring: false,
      cost: 4000, monthlyCost: 0,
      description: 'City planning. Fast-tracks YOUR permits, blocks THEIRS.',
      effect: 'instant_permit',
      heatGain: 12,
      unlock: 1,
    },
    {
      id: 'connie', name: 'Connie "Clean"', icon: '💼',
      type: 'launder', recurring: true,
      cost: 1200, monthlyCost: 1200,
      description: 'Creative accountant. Turns dirty money into... pizza profits.',
      effect: 'launder_money',
      heatGain: 5,
      unlock: 1,
    },
    {
      id: 'don_caruso', name: 'Don Caruso', icon: '🕴️',
      type: 'protection', recurring: true,
      cost: 12000, monthlyCost: 12000,
      description: 'The man himself. Full protection. Nobody touches you.',
      effect: 'full_protection',
      heatGain: 0,
      unlock: 3,
    },
  ],
};
