#!/usr/bin/env python3
"""
Generates data/plan.json: a 70-week (16-month) couch-to-Ironman training plan.

Structure: six phases, each one calendar quarter (13 weeks) except the final
taper month (5 weeks), totalling 70 weeks / 16 months:

  A. Foundation        weeks  1-13  (months  1-3)
  B. Sprint Build       weeks 14-26  (months  4-6)  -> Sprint Triathlon
  C. Olympic Build      weeks 27-39  (months  7-9)  -> Olympic/Standard Triathlon
  D. Half-Iron Build    weeks 40-52  (months 10-12) -> Half-Iron (70.3)
  E. Ironman Build      weeks 53-65  (months 13-15) -> peak volume, no race
  F. Taper & Race       weeks 66-70  (month  16)    -> Full Ironman (140.6)

Within phases A-E, every 4th week (global week % 4 == 0) is a recovery
("cutback") week: run/bike/swim/brick volume is reduced ~25% so the body
absorbs the previous three weeks of build. Phase F is a hand-authored
monotonic taper, not generated by interpolation.

Weeks 1-21 (months 1-5) also layer in extra weekly runs, loosely mirroring a
novice marathon build-up that runs alongside the triathlon work: weeks 1-13
add a second run, and weeks 9-21 add a third. Instead of lerping each run
session independently, these weeks target an explicit total of weekly
running minutes (see MARATHON_RUN_RANGES, ramping 30-60 in month 1 up to
330-430 in month 5) and split that total across the week's run sessions by
fixed proportion, so the build reaches marathon-appropriate volume on
schedule. The weekly total still gets the same recovery-week cutback as
every other discipline. From week 22 on, run volume reverts to its
original, independently-lerped curves.

Run this script directly to (re)write ../data/plan.json.
"""
import json
import os

WEEKS_PER_PHASE = 13
TOTAL_WEEKS = 70


def round5(x):
    return int(round(x / 5.0) * 5)


def round50(x):
    return int(round(x / 50.0) * 50)


def lerp(start, end, i, n):
    """Linear interpolation for step i (0-indexed) of n total steps."""
    if n <= 1:
        return end
    return start + (end - start) * (i / (n - 1))


def is_recovery_week(global_week):
    return global_week % 4 == 0


def recovery_scale(global_week):
    return 0.75 if is_recovery_week(global_week) else 1.0


# Target total run-discipline minutes per week, by month, for the novice
# marathon build-up layered into weeks 1-21 (see module docstring).
MARATHON_RUN_RANGES = {
    1: (30, 60),
    2: (75, 130),    # +10% over original (70, 120)
    3: (150, 230),   # +15% over original (130, 200)
    4: (275, 360),   # +20% over original (230, 300)
    5: (410, 540),   # +25% over original (330, 430)
}

# Exact week range covered by each of those months (month 3 runs 5 weeks so
# every 13-week phase still splits 4/4/5, matching MONTH_WEEK_BOUNDARIES).
MARATHON_MONTH_WEEKS = {
    1: (1, 4),
    2: (5, 8),
    3: (9, 13),
    4: (14, 17),
    5: (18, 21),
}


def weekly_run_target(global_week):
    """Total run-discipline minutes targeted for this week, lerped across its
    month's range and recovery-scaled like every other discipline."""
    for month, (start, end) in MARATHON_MONTH_WEEKS.items():
        if start <= global_week <= end:
            low, high = MARATHON_RUN_RANGES[month]
            n = end - start + 1
            local_i = global_week - start
            return lerp(low, high, local_i, n) * recovery_scale(global_week)
    return None


def session(discipline, title, detail, duration_min=None, distance_m=None):
    s = {"discipline": discipline, "title": title, "detail": detail}
    if duration_min is not None:
        s["durationMin"] = duration_min
    if distance_m is not None:
        s["distanceM"] = distance_m
    return s


def rest_day():
    return []


REST_DETAIL = "Full rest day. Sleep, hydration, and easy stretching pay off here as much as any workout."


def run_detail(mins, tempo=False, hills=False):
    if hills:
        return f"{mins} min run with rolling hills or 4-6 short hill efforts — steady effort on the climbs, relaxed on the descents."
    if tempo:
        return f"{mins} min run — 10 min easy warm-up, then steady-hard tempo effort, 5 min easy cool-down."
    return f"{mins} min easy run — keep it conversational; consistent form matters more than pace."


def swim_detail(meters, phase):
    if phase == "A":
        return f"{meters}m total in the pool — mix of drills (catch-up, kick sets) and short easy swims with rest as needed. Technique over speed."
    if phase in ("B", "C"):
        return f"{meters}m — warm-up, then continuous-style swimming at a steady aerobic pace, short rest between sets as needed."
    return f"{meters}m long continuous swim — steady aerobic effort; if open water is available, practice sighting every 6-8 strokes."


def bike_detail(mins, tempo=False):
    if tempo:
        return f"{mins} min bike — warm up easy, then 3x8 min at a steady-hard effort with easy spinning recovery between, cool down easy."
    return f"{mins} min easy bike — flat-to-rolling terrain, conversational effort."


def brick_detail(bike_mins, run_mins):
    return (f"Bike {bike_mins} min steady, then Run {run_mins} min immediately off the bike. "
            "Practice the transition — the first few minutes of the run will feel heavy on tired legs; that's normal.")


def long_bike_detail(mins, brick_run_mins=None):
    base = f"{mins} min long ride — steady aerobic effort; practice race nutrition/hydration every 20-30 min."
    if brick_run_mins:
        base += f" Finish with a {brick_run_mins} min easy run straight off the bike."
    return base


def long_run_detail(mins):
    return f"{mins} min long run — steady aerobic pace; practice the nutrition/hydration you'd use on race day."


def strength_detail(mins):
    return f"{mins} min strength & mobility — core, glutes, hips, plus 5-10 min stretching or foam rolling."


MILESTONES = [
    {
        "week": 26,
        "label": "Sprint Triathlon",
        "emoji": "\U0001F3C1",
        "distances": "750m swim / 20km bike / 5km run",
        "note": "Your first triathlon finish line! Race at an easy-hard effort and enjoy it — everything since week 1 has led here.",
    },
    {
        "week": 39,
        "label": "Olympic Triathlon",
        "emoji": "\U0001F3C1",
        "distances": "1.5km swim / 40km bike / 10km run",
        "note": "Double the sprint distance. Pace the bike conservatively so the 10K run doesn't fall apart.",
    },
    {
        "week": 52,
        "label": "Half-Iron Triathlon (70.3)",
        "emoji": "\U0001F3C1",
        "distances": "1.9km swim / 90km bike / 21.1km run",
        "note": "A huge benchmark — if you finish this feeling strong, the full distance is a question of patience, not fitness.",
    },
    {
        "week": 70,
        "label": "Full Ironman (140.6)",
        "emoji": "\U0001F947",
        "distances": "3.86km swim / 180km bike / 42.2km run",
        "note": "Race day. Sixteen months of work for this one. Trust your pacing, fuel early and often, and smile at mile 20 — you earned it.",
    },
]
MILESTONE_BY_WEEK = {m["week"]: m for m in MILESTONES}


def phase_a_week(local_i, n, global_week):
    """Foundation: weeks 1-13. Run, Swim, Bike, Strength, plus a second weekly
    run throughout and a third from week 9 on (see module docstring)."""
    scale = recovery_scale(global_week)
    swim_m = round50(lerp(400, 800, local_i, n) * scale)
    bike_m = round5(lerp(20, 50, local_i, n) * scale)
    strength_m = round5(lerp(20, 30, local_i, n))

    days = [rest_day() for _ in range(7)]
    days[3] = [session("swim", "Technique Swim", swim_detail(swim_m, "A"), distance_m=swim_m)]
    days[5] = [session("bike", "Easy Bike", bike_detail(bike_m), duration_min=bike_m)]
    days[6] = [session("strength", "Strength & Mobility", strength_detail(strength_m), duration_min=strength_m)]

    total = weekly_run_target(global_week)
    if global_week >= 9:
        run_m = max(10, round5(total * 0.45))
        second_m = max(10, round5(total * 0.30))
        third_m = max(10, round5(total * 0.25))
        days[2] = [session("run", "Short Run", run_detail(third_m), duration_min=third_m)]
    else:
        run_m = max(10, round5(total * 0.60))
        second_m = max(10, round5(total * 0.40))

    days[1] = [session("run", "Easy Run", run_detail(run_m), duration_min=run_m)]
    days[4] = [session("run", "Recovery Run", run_detail(second_m), duration_min=second_m)]
    return days


def phase_b_week(local_i, n, global_week):
    """Sprint Build: weeks 14-26. Adds brick (bike+run) from week 18 onward,
    and a third weekly run (day2) through week 21 — see module docstring."""
    scale = recovery_scale(global_week)
    swim_m = round50(lerp(800, 1200, local_i, n) * scale)
    bike_m = round5(lerp(40, 60, local_i, n) * scale)

    days = [rest_day() for _ in range(7)]
    days[3] = [session("swim", "Endurance Swim", swim_detail(swim_m, "B"), distance_m=swim_m)]
    days[4] = [session("bike", "Tempo Bike", bike_detail(bike_m, tempo=True), duration_min=bike_m)]

    if global_week <= 21:
        total = weekly_run_target(global_week)
        run_m = max(10, round5(total * 0.35))
        third_m = max(10, round5(total * 0.25))
        long_run_m = max(10, round5(total * 0.40))
        days[2] = [session("run", "Recovery Run", run_detail(third_m), duration_min=third_m)]
    else:
        run_m = round5(lerp(30, 40, local_i, n) * scale)
        long_run_m = round5(lerp(30, 55, local_i, n) * scale)

    days[1] = [session("run", "Run + Core", run_detail(run_m) + " Finish with a 10 min core circuit.", duration_min=run_m)]

    if global_week < 18:
        sat_bike_m = round5(lerp(45, 55, local_i, n) * scale)
        days[5] = [session("bike", "Steady Bike", bike_detail(sat_bike_m), duration_min=sat_bike_m)]
    else:
        bb = round5(lerp(55, 70, local_i, n) * scale)
        br = round5(lerp(10, 20, local_i, n) * scale)
        days[5] = [session("brick", "Brick: Bike + Run", brick_detail(bb, br))]

    if global_week == 26:
        m = MILESTONE_BY_WEEK[26]
        days[6] = [session("race", f"RACE DAY: {m['label']}", f"{m['distances']}. {m['note']}")]
    else:
        days[6] = [session("run", "Long Run", long_run_detail(long_run_m), duration_min=long_run_m)]
    return days


def phase_c_week(local_i, n, global_week):
    """Olympic Build: weeks 27-39. Same weekly shape as Phase B, higher volume, weekly brick."""
    scale = recovery_scale(global_week)
    run_m = round5(lerp(40, 50, local_i, n) * scale)
    swim_m = round50(lerp(1200, 1800, local_i, n) * scale)
    bike_m = round5(lerp(60, 75, local_i, n) * scale)
    bb = round5(lerp(70, 95, local_i, n) * scale)
    br = round5(lerp(20, 30, local_i, n) * scale)
    long_run_m = round5(lerp(55, 75, local_i, n) * scale)

    days = [rest_day() for _ in range(7)]
    days[1] = [session("run", "Tempo Run", run_detail(run_m, tempo=True), duration_min=run_m)]
    days[3] = [session("swim", "Endurance Swim", swim_detail(swim_m, "C"), distance_m=swim_m)]
    days[4] = [session("bike", "Tempo Bike", bike_detail(bike_m, tempo=True), duration_min=bike_m)]
    days[5] = [session("brick", "Brick: Bike + Run", brick_detail(bb, br))]

    if global_week == 39:
        m = MILESTONE_BY_WEEK[39]
        days[6] = [session("race", f"RACE DAY: {m['label']}", f"{m['distances']}. {m['note']}")]
    else:
        days[6] = [session("run", "Long Run", long_run_detail(long_run_m), duration_min=long_run_m)]
    return days


def phase_d_week(local_i, n, global_week):
    """Half-Iron Build: weeks 40-52. Long bike grows large; brick run-finisher added from week 43."""
    scale = recovery_scale(global_week)
    run_m = round5(lerp(45, 55, local_i, n) * scale)
    swim_m = round50(lerp(1800, 2400, local_i, n) * scale)
    bike_m = round5(lerp(60, 75, local_i, n) * scale)
    long_bike_m = round5(lerp(95, 180, local_i, n) * scale)
    long_run_m = round5(lerp(75, 100, local_i, n) * scale)

    days = [rest_day() for _ in range(7)]
    days[1] = [session("run", "Tempo Run", run_detail(run_m, tempo=True), duration_min=run_m)]
    swim_note = swim_detail(swim_m, "D")
    if global_week >= 46:
        swim_note += " If you have access to open water, this is a great week to practice in it."
    days[3] = [session("swim", "Endurance Swim", swim_note, distance_m=swim_m)]
    days[4] = [session("bike", "Tempo Bike", bike_detail(bike_m, tempo=True), duration_min=bike_m)]

    if global_week >= 43:
        finisher = round5(lerp(15, 20, local_i, n) * scale)
        days[5] = [session("brick", "Long Bike + Run Finisher", long_bike_detail(long_bike_m, finisher))]
    else:
        days[5] = [session("bike", "Long Bike", long_bike_detail(long_bike_m), duration_min=long_bike_m)]

    if global_week == 52:
        m = MILESTONE_BY_WEEK[52]
        days[6] = [session("race", f"RACE DAY: {m['label']}", f"{m['distances']}. {m['note']}")]
    else:
        days[6] = [session("run", "Long Run", long_run_detail(long_run_m), duration_min=long_run_m)]
    return days


def phase_e_week(local_i, n, global_week):
    """Ironman Build: weeks 53-65. Peaks at week 63 (local index 10), then plateaus
    for weeks 64-65 so the build doesn't hit its absolute max in the week before taper."""
    peak_i = 10  # local index of week 63
    ramp_n = peak_i + 1
    base_i = min(local_i, peak_i)
    scale = recovery_scale(global_week)

    run_m = round5(lerp(45, 60, base_i, ramp_n) * scale)
    swim_m = round50(lerp(2400, 3800, base_i, ramp_n) * scale)
    bike_m = round5(lerp(60, 75, base_i, ramp_n) * scale)
    long_bike_m = round5(lerp(180, 330, base_i, ramp_n) * scale)
    long_run_m = round5(lerp(100, 180, base_i, ramp_n) * scale)

    days = [rest_day() for _ in range(7)]
    days[1] = [session("run", "Tempo/Hills Run", run_detail(run_m, hills=(global_week % 2 == 0)), duration_min=run_m)]
    days[3] = [session("swim", "Long Swim", swim_detail(swim_m, "E"), distance_m=swim_m)]
    days[4] = [session("bike", "Steady Bike", bike_detail(bike_m), duration_min=bike_m)]
    days[5] = [session("bike", "Long Bike", long_bike_detail(long_bike_m), duration_min=long_bike_m)]
    days[6] = [session("run", "Long Run", long_run_detail(long_run_m) + " This is Ironman-specific endurance work — patience over pace.", duration_min=long_run_m)]
    return days


# Phase F: hand-authored taper, weeks 66-70 (local index 0-4). Not generated by interpolation.
PHASE_F_WEEKS = [
    {"run": 35, "swim": 2000, "bike": 50, "long_bike": 150, "brick_run": 15, "long_run": 90},
    {"run": 30, "swim": 1500, "bike": 45, "long_bike": 100, "brick_run": None, "long_run": 60},
    {"run": 20, "swim": 1000, "bike": 30, "long_bike": 60, "brick_run": None, "long_run": 40},
    {"run": 15, "swim": 800, "bike": 20, "long_bike": 30, "brick_run": None, "long_run": 20},
]


def phase_f_week(local_i, global_week):
    days = [rest_day() for _ in range(7)]
    if local_i < 4:
        w = PHASE_F_WEEKS[local_i]
        days[1] = [session("run", "Taper Run", run_detail(w["run"]), duration_min=w["run"])]
        days[3] = [session("swim", "Taper Swim", swim_detail(w["swim"], "E"), distance_m=w["swim"])]
        days[4] = [session("bike", "Taper Bike", bike_detail(w["bike"]), duration_min=w["bike"])]
        if w["brick_run"]:
            days[5] = [session("brick", "Long Bike + Run Finisher", long_bike_detail(w["long_bike"], w["brick_run"]))]
        else:
            days[5] = [session("bike", "Easy Long Bike", long_bike_detail(w["long_bike"]), duration_min=w["long_bike"])]
        days[6] = [session("run", "Long Run", long_run_detail(w["long_run"]))]
    else:
        # Final week: race week. Very light touches, full rest before race day.
        days[1] = [session("bike", "Easy Spin", "15 min easy spin, just to keep the legs loose. Should feel like nothing.", duration_min=15)]
        days[3] = [session("run", "Shakeout Jog", "10-15 min easy jog + a few strides. Check that race-day shoes/gear feel good.", duration_min=15)]
        days[5] = [session("swim", "Pre-Race Loosener", "10 min easy swim, just to feel the water. Lay out gear and review your nutrition plan.", distance_m=400)]
        m = MILESTONE_BY_WEEK[70]
        days[6] = [session("race", f"RACE DAY: {m['label']}", f"{m['distances']}. {m['note']}")]
    return days


PHASES = [
    {"key": "A", "name": "Foundation", "weeks": (1, 13), "fn": phase_a_week},
    {"key": "B", "name": "Sprint Build", "weeks": (14, 26), "fn": phase_b_week},
    {"key": "C", "name": "Olympic Build", "weeks": (27, 39), "fn": phase_c_week},
    {"key": "D", "name": "Half-Iron Build", "weeks": (40, 52), "fn": phase_d_week},
    {"key": "E", "name": "Ironman Build", "weeks": (53, 65), "fn": phase_e_week},
    {"key": "F", "name": "Taper & Race", "weeks": (66, 70), "fn": phase_f_week},
]

DAY_LABELS = ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"]

# Each 13-week phase (A-E) covers 3 real months, split 4/4/5 weeks so every
# month has a sensible length. Phase F (5 weeks) is simply month 16.
MONTH_WEEK_BOUNDARIES = [4, 8, 13]


def month_for(phase_index, local_i, phase_key):
    if phase_key == "F":
        return 16
    local_month = next(i for i, boundary in enumerate(MONTH_WEEK_BOUNDARIES) if local_i < boundary)
    return phase_index * 3 + local_month + 1


def build_plan():
    weeks_out = []
    for phase_index, phase in enumerate(PHASES):
        start, end = phase["weeks"]
        n = end - start + 1
        for local_i in range(n):
            global_week = start + local_i
            month = month_for(phase_index, local_i, phase["key"])
            if phase["key"] == "F":
                days_raw = phase["fn"](local_i, global_week)
            else:
                days_raw = phase["fn"](local_i, n, global_week)

            days = [{"label": DAY_LABELS[i], "sessions": days_raw[i]} for i in range(7)]
            weeks_out.append({
                "week": global_week,
                "month": month,
                "phase": phase["name"],
                "phaseKey": phase["key"],
                "isRecoveryWeek": is_recovery_week(global_week) and phase["key"] != "F",
                "milestone": MILESTONE_BY_WEEK.get(global_week),
                "days": days,
            })

    assert len(weeks_out) == TOTAL_WEEKS, f"expected {TOTAL_WEEKS} weeks, got {len(weeks_out)}"
    return {
        "totalWeeks": TOTAL_WEEKS,
        "totalMonths": 16,
        "phases": [{"key": p["key"], "name": p["name"], "startWeek": p["weeks"][0], "endWeek": p["weeks"][1]} for p in PHASES],
        "milestones": MILESTONES,
        "weeks": weeks_out,
    }


def main():
    plan = build_plan()
    out_path = os.path.join(os.path.dirname(__file__), "..", "data", "plan.json")
    out_path = os.path.normpath(out_path)
    with open(out_path, "w") as f:
        json.dump(plan, f, indent=2)
        f.write("\n")
    print(f"Wrote {out_path} ({plan['totalWeeks']} weeks, {sum(1 for w in plan['weeks'] for d in w['days'] if d['sessions'])} active days)")


if __name__ == "__main__":
    main()
